os: Linux
dist: focal
language: node_js
node_js: 18.19.0
install: skip
script: sleep 1
deploy:
  provider: npm
  email: "the.tim.harrison10@gmail.com"
  api_key: 
    secure: "${NPM_API_KEY}"
  skip_cleanup: true
  on:
    tags: true
